meta_product_name: "La Santerre Cup"
meta_title: "La Santerre Cup - Visons plus qu'une victoire !"
meta_description: "La Santerre Cup est un tournoi de football qui rassemble le
temps d’une journée et d’une soirée 500 jeunes autour de projets solidaires.
Association loi de 1901 depuis 2017, tous les bénéfices réalisés lors de chaque
édition sont reversés à des associations caritatives."
meta_image: "homepage.jpg" # should exist in `app/assets/images/`
